# (APPENDIX) পরিশিষ্ট {-}

সবগুলো পরিশিষ্টই অনুবাদক যোগ করেছেন। 

# মহাবিশ্বের সম্ভাব্য পরিণতি {#fate}

গত শতকে আমরা জানতে পারি, মহাবিশ্বের একটি নির্দিষ্ট অতীত আছে। তার আগে স্থির অবস্থা তত্ত্ব জনপ্রিয় ছিল। ধারণা করা হত, মহাবিশ্ব অনন্তকাল ধরে উপস্থিত আছে। বয়স অনন্ত হলে ভবিষ্যৎ পরিণতি নিয়ে প্রশ্ন আসে না। কিন্তু কবির কথা, “জন্মিলে মরিতে হবে।“ তাই ভবিষ্যতে কী হবে সেটা বড় এক প্রশ্ন। 

১৯২০ সাল থেকে ১৯৫০। এই বিশ বছর ধরে বিজ্ঞানী এডউইন হাবলের পর্যবেক্ষণের মাধ্যমে পরিষ্কার বোঝা গেল, ছায়াপথরা একে অপর থেকে দূরে সরছে। এ থেকেই তৈরি হয় বিগ ব্যাং তত্ত্ব। ১৯২৭ সালে জর্জ লেমেইত্র বলেন, প্রসারণশীল মহাবিশ্ব থেকে বলা যায়, অতীতে মহাবিশ্ব ছিল নিবিড় এক বিন্দুর মতো। এর আগে আইনস্টাইনের সার্বিক আপেক্ষিক তত্ত্বের সমাধান করে আলেকজান্ডার ফ্রিডম্যানও একই কথা বলেছিলেন। আইনস্টাইনের সমীকরণের একটি সমাধান অনুসারে দেখা যায়, একটি প্রাথমিক সিংগুলারিটি থেকে জন্ম মহাবিশ্বের। ১৯৬৪ সালে আবিষ্কৃত হয় মহাজাগতিক পটভূমি বিকিরণ। বিগ ব্যাং এর পক্ষে একটি বড় প্রমাণ একটি। 

১৯৯৮ সাল থেকে শুরু করে বিভিন্ন পর্যবেক্ষণ থেকে দেখা যায়, মহাবিশ্বের প্রসারণের গতি ক্রমেই বাড়ছে। এর জন্য দায়ী শক্তিকে নাম দেওয়া হয় ডার্ক এনার্জি। আইনস্টাইনের সমীকরণ বলছিল, মহাবিশ্ব প্রসারিত হচ্ছে। কিন্তু আইনস্টাইন নিজেই সেটা বিশ্বাস করতেন না। সমীকরণ অসম্পূর্ণ মনে করে তিনি তাই বাড়তি একটি ধ্রুবক যোগ করেছিলেন। পরে স্বীকার করেন, এটা তার জীবনের সবচেয়ে বড় ভুল। কিন্তু এখন আবার মনে হচ্ছে এই ধ্রুবক দরকার আছে। এই ধ্রুবক আসলে ডার্ক এনার্জির বিপরীতে কাজ করে। 

ভবিষ্যতে মহাবিশ্বের ভাগ্যে মোটা দাগে বললে তিনটি ঘটনা ঘটতে পারে। হয় এটি চিরকাল প্রসারিত হতে থাকবে। মহাকর্ষ প্রসারণের গতি কমানোর চেষ্টা করবে। তবে ডার্ক এনার্জির কারণে প্রসারণের গতি ক্রমেই বাড়বে। আরেকটি হতে পারে, মহাবিশ্বের প্রসারণ এক সময় থেমে যাবে। শুরু হবে সঙ্কোচন। আরেকটি সম্ভাবনা হলো, প্রসারণ চলতে থাকবে। তবে প্রসারণের গতি ক্রমশ কমতে থাকবে। কিন্তু একেবারে বন্ধ হয়ে যাবে না। 

ভবিষ্যতে মহাবিশ্বের ভাগ্যে কী ঘটবে তার বড় একটি প্রভাবক হলো মহাবিশ্বের ঘনত্ব পরামিতি (density parameter)। একে গ্রিক বর্ণ ওমেগা (Ω) দিয়ে প্রকাশ করা হয়। এর মান পেতে মহাবিশ্বের বস্তুর গড় ঘনত্বকে ঘনত্বের একটি ক্রান্তি মান দ্বারা ভাগ করা হয়। ঘনত্বের যে মান খুব অল্পের জন্য মহাবিশ্বের প্রসারণকে থামাতে বন্ধ হবে তার নাম ক্রান্তি (critical) ঘনত্ব। 
মহাবিশ্বের ভবিষ্যতের সাথে এর আকৃতিরও সম্পর্ক আছে। ওমেগার মান ১-এর বেশি হলে মহাবিশ্বের আকৃতি হবে আবদ্ধ গোলকের পৃষ্ঠের মতো। কারণ এক্ষেত্রে মহাবিশ্বের ঘনত্ব ক্রান্তি ঘনত্বের চেয়ে বেশি। পৃথিবীর পৃষ্ঠের মতো এমন মহাবিশ্বের ত্রিভুজের তিন কোণের যোগফল ১৮০ ডিগ্রির বেশি হবে। তবে বড় মাপকাঠিতে মহাবিশ্বের আকৃতি হবে উপবৃত্তের মতো। মহাকর্ষের প্রভাবে এক সময় প্রসারণ থেমে যাবে। শেষ পর্যন্ত ঘটবে বিগ ক্রাঞ্চ (Big Crunch) বা মহাসঙ্কোচন। বিন্দু থেকে আসা মহাবিশ্ব বিন্দুতে গিয়েই আবার মিশে যাবে। 

তবে কিছু কিছু আধুনিক তত্ত্ব বলছে, ওমেগার মান ১-এর বেশি হলেও ডার্ক এনার্জির প্রভাবে মহাবিশ্ব প্রসারিত হতেই থাকবে। এ কারণে মহাসঙ্কোচন ঘটার সম্ভাবনা এখন পর্যন্ত অর্জিত জ্ঞান অনুসারে কম। তবে ঘটবেই না সেটা বলার জো নেই। 
ওমেগার মান ১-এর কম হলে মহাবিশ্ব হবে উন্মুক্ত। ত্রিভুজের তিন কোণের যোগফল ১৮০ ডিগ্রির কম হবে। মহাকর্ষ প্রসারণকে কিছুটা কমাবে। কিন্তু ডার্ক এনার্জির প্রভাবে সে বাধা উপেক্ষা করে প্রসারণের গতি বরং আরও বেড়ে যেতে থাকবে। এভাবে চলতে থাকলে একসময় মহাকর্ষ, তড়িচ্চুমকত্ব ও সবল নিউক্লীয় বলের বাঁধন ছিঁড়ে যাবে। এ অবস্থাকে বলা হয় বিগ রিপ (Big Rip) বা মহাভাঙন। 

একই রকম পরিস্থিতিতে আরেকটি সম্ভাব্য পরিণতির নাম বিগ ফ্রিজ (Big Freeze) বা মহাহিমায়ন। এ অবস্থায় সর্বত্র বিরাজ করবে হিমশীতল অবস্থা। হবে না কোনোরকম তাপ বিনিময়। থেমে যাব বস্তুকণার চলাচল। এ কারণে এর অপর নাম তাপীর মৃত্যু। এটা ঘটে গেলে বস্তুর মধ্যে আর কোনো প্রকার তাপ বিনিময় সম্ভব হবে না। সব যন্ত্র অচল হয়ে যাবে। এনট্রপি (শক্তি রূপান্তরের অক্ষমতা) হবে সর্বোচ্চ। 

তবে মহাবিশ্বের ঘনত্ব ক্রান্তি ঘনত্বের সমানও হয়ে যেতে পারে। সত্যি বলতে, বর্তমান পর্যবেক্ষণ এর পক্ষেই কথা বলছে। এমন মহাবিশ্বেই ত্রিভুজের তিন কোণের যোগফল ১৮০ ডিগ্রি হয়। এক্ষেত্রে মহাবিশ্ব হবে সমতল। পর্যবেক্ষণ বলছে, মহাবিশ্ব এমনই। এই ফলাফলের ত্রুটির মাত্রা মাত্র ০.৪%। এই মহাবিশ্বও চিরকাল প্রসারিত হবে, তবে প্রসারণের হার ক্রমশ কমবে। তবে কখনোই একেবারে থেমে যাবে না। তবে ডার্ক এনার্জি ভূমিকা রাখলে প্রসারণ শুরুতে থামলেও আবার বেড়ে যাবে। পরিণতি হবে সেই উন্মুক্ত মহাবিশ্বের মতোই। 

আরও কিছু কমসম্ভাব্য ঘটনা ঘটতে পারে মহজাবিশ্বের ভাগ্যে। এর একটি হলো বিগ বাউন্স। এটা আসলে মহাবিশ্ব সম্পর্কে চক্রাকার মডেলের একটি অংশ। এটি অনুসারে, মহাবিশ্ব শুরু হয়েছিল সঙ্কুচিত অবস্থা থেকে। আর সেই সঙ্কুচিত অবস্থাটা এসেছিল তার পূর্ববর্তী একটি প্রসারণ থেমে গিয়ে গুটিয়ে যাওয়ার মাধ্যমে। এভাবেই মহাবিশ্ব একের পর সঙ্কুচিত ও প্রসারিত হচ্ছে। একের পর ঘটছে বিগ ব্যাং ও বিগ ক্রাঞ্চ। এ জন্যেই এই মডেলের নাম চক্রাকার মডেল। 

বিজ্ঞানীরা বলছেন আরও একটি সম্ভাবনার কথা। এর নাম বিগ স্লার্প (Big Slurp)। স্লার্প অর্থ গ্রাস করা বা গ্রাস করার সময় সৃষ্ট শব্দ। এ তত্ত্ব অনুসারে মহাবিশ্ব এখন নকল ভ্যাকুয়াম অবস্থায় আছে। যেকোনো সময় চলে যেতে পারে প্রকৃত ভ্যাকুয়ামে। প্রকৃতির যেকোনো ভৌত প্রক্রিয়া সবসময় সর্বিনিম্নের শক্তির অবস্থানে থাকতে চায়। আর মহাবিশ্ব সর্বনিম্ন শক্তির অবস্থায় থাকলেই কেবল প্রকৃত ভ্যাকুয়ামে থাকবে। এখন সেটা নাও হতে পারে। হয়ত মহাবিশ্ব এখন উচ্চতর শক্তির অবস্থানে আছে। তার মানে আছে নকল ভ্যাকুয়াম অবস্থায়। সেক্ষেত্রে যেকোনো সময় এটি আসল ভ্যাকুয়ামে চলে যাবে। তার সাথে সাথে আমূল পাল্টে যাবে আমাদের চিরচেনা মহাবিশ্ব। ভৌত ধ্রুবকদের মান বদলে যেতে পারে। পাল্টে যেতে পারে আলোর বেগের মান কিংবা অ্যাভোগেড্রো ধ্রুবক। ফলে স্থান, কাল, বস্তু ও শক্তির ধারণা একদম বদলে যেতে পারে। হয়ত আগাম কোনো সঙ্কেত না দিয়েই ধ্বংস হয়ে যাবে মহাবিশ্ব। 
বিষয়টি নিয়ে বিস্তারিত আলোচনা করা হয়েছে এগারশ ও তৃতীয় অধ্যায়ে। 