--- 
title: "লাস্ট থ্রি মিনিটস"
author: "আব্দুল্যাহ আদিল মাহমুদ"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: mahmudstat/l3m
description: "লাস্ট থ্রি মিনিটস বইয়ের অনুবাদ"
---

# ভূমিকা {-}

১৯৬০ এর দশকের শুরুর দিকের কথা। আমি ছাত্র তখন। মহাবিশ্বের শুরুর  রহস্য জানার অপরিসীম কৌতূহল সবার চোখে-মুখে। বিগ ব্যাং তত্ত্বের জন্ম সেই ১৯২০ এর দশকে হলেও একে গুরুত্বের সাথে নেওয়া শুরু ১৯৫০ এর দশকের পরে। সবাই এর সাথে পরিচিত থাকলেও তত্ত্বটি তখনও তেমন কোনো আস্থা অর্জন করতে পারেনি। ওদিকে শক্ত প্রতিদ্বন্দ্বী হিসেবে আছে স্থির অবস্থা তত্ত্ব (steady-state theory)। মহাবিশ্বের কোনো শুরু থাকতে পারে সে সম্ভাবনাই এটি নাকচ করে দিয়েছে। বিভিন্ন মহলের কাছে এটি তখনও সবচেয়ে গহণযোগ্য তত্ত্ব। এরপর ১৯৬৫ সালে এল রবার্ট পেনজিয়াস ও আর্নো উইলসনের আবিষ্কার এল। মহাজাগতিক পটভূমি তাপ বিকিরণ। দৃশ্যপট পুরোপুরি পাল্টে গেল। পরিষ্কারভাবে প্রমাণিত হলো, একটি উত্তপ্ত, উন্মত্ত ও আকস্মিক অবস্থা থেকে শুরু মহাবিশ্বের। 

কসমোলজিস্টরা এই আবিষ্কারের ফলাফল বের করতে উঠেপড়ে লাগলেন। বিগ ব্যাংয়ের ১০ লাখ বছর পরে মহাবিশ্ব কতটা উত্তপ্ত ছিল? এক বছর পর? এক সেকেন্ড পর? সেই প্রারম্ভিক চুল্লিতে কোন ধরনের ভৌত প্রক্রিয়া সংঘটিত হয়েছিল? সৃষ্টির শুরর কোনো ধ্বংসাবশেষ বাকি আছে কি? যা থেকে জানা যাবে সেই সময়ের চরম অবস্থার খবর। 

আমার ভালোমতো মনে আছে, ১৯৬৮ সালে একটি লেকচার শুনতে গিয়েছিলাম। সবশেষে অধ্যাপক পটভূমি তাপ বিকিরণের (cosmic background heat radiation) আবিষ্কারের আলোকে বিগ ব্যাং নিয়ে কথা বললেন। হাসিমুখে বললেন, “বিগ ব্যাং এর পরের প্রথম তিন মিনিটে সংঘটিত নিউক্লিয় প্রক্রিয়ার ওপর ভিত্তি করে কিছু তাত্ত্বিক মহাবিশ্বের রাসায়নিক উপাদানের বিবরণ দিয়েছেন।” দর্শকরা হাসিতে ফেটে পড়লেন। মহাবিশ্বের জন্মের মাত্র সামান্য সময় পরের অবস্থার বিবরণ দেওয়ার চেষ্টা কতই না হাস্যকর! এমনকি সপ্তদশ শতকের যাজক জেমস উশারও এমন দুঃসাহস করেননি। অথচ তিনিই কিন্তু বাইবেলের ক্রমানুপুঞ্জির ওপর ভিত্তি করে দাবি করেছিলেন, ৪০০৪ খৃষ্টপূর্ব সালের ২৩ অক্টোবর তারিখে সৃষ্টি হয়েছিল মহাবিশ্বের। প্রথম তিন মিনিটের ঘটনা প্রবাহের নিখুঁত বর্ণনা কিন্তু তিনিও দিতে চেষ্টা করেননি। 

কিন্তু মহাজাগতিক তাপ বিকিরণ আবিষ্কারের মাত্র এক দশকের মধ্যেই পাল্টে গেল বিজ্ঞানের গতি । প্রথম তিন মিনিট ছাত্রদেরও মনোযোগ কেড়ে নিল। বই লেখা হতে লাগল। ১৯৭৭ সালে অ্যামেরিকান পদার্থবিদ ও কসমোলজিস্ট স্টিভেন উইনবার্গ লিখলেন একটি বেস্ট সেলার বই। শিরোনাম দ্য ফার্স্ট থ্রি মিনিটস বা প্রথম তিন মিনিট। জনপ্রিয় বিজ্ঞান প্রকাশনার জগতে এটি নতুন ধারার প্রবর্তন করে। লেখক বিশ্ববিখ্যাত একজন পণ্ডিত। বিগ ব্যাংয়ের ঠিক পরের প্রক্রিয়াগুলো সাধারণ পাঠকের জন্যে লিখেছেন বিস্তারিত ও বোধগম্য করে।

এক দিকে উত্তেজক আবিষ্কারগুলো সাধারণ মানুষ আস্তে আস্তে বুঝতে শুরু করেছেন। ওদিকে বিজ্ঞানীরাও বসে নেই। আগ্রহের বিষয় গেল পাল্টে। এক সময় আগ্রহের বিষয় ছিল মহাবিশ্বের প্রারম্ভিক অবস্থার খোঁজ জানা। মানে জন্মের প্রায় কয়েক মিনিট পরের কথা। আর এখন আগ্রহের বিষয় হয়ে গেলে তারও অনেক আগের খবর। জন্মের এক সেকেন্ডের প্রায় অসীম ভগ্নাংশ সময় পরের অবস্থা। তার প্রায় এক দশক পরে ব্রিটিশ গাণিতিক পদার্থবিদ স্টিফের হকিং লিখলেন অ্যা ব্রিফ হিস্টরি অব টাইম। এক সেকেন্ডের দশ কোটি কোটি কোটি কোটি কোটি ভাগের এক ভাগ সময়ে কী ঘটেছিল তাও বললেন তিনি। ১৯৬৮ সালের সেই লেকচারের শেষ হাসিটুকই আজ হাস্যকর হয়ে গেছে। 

বিগ ব্যাং তত্ত্ব এখন বিজ্ঞানী ও সাধারণ মানুষের আস্থা অর্জন করে ফেলেছে। ফলে এখন বেশি চিন্তা-ভাবনা চলছে মহাবিশ্বের ভবিষ্যত নিয়ে। মহাবিশ্বের শুরুর খবর আমরা ভালোই জানি। কিন্তু এর পরিণতি কেমন হবে? এর চূড়ান্ত  পরিণতি সম্পর্কে কী বলা যায়? শেষও কি হবে ব্যাং (বিস্ফোরণ) বা আর্তনাদের মাধ্যমে? বা আদৌ কি এর শেষ আছে? আমাদেরই বা কী হবে? আমরা বা আমাদের পরের প্রজন্ম কি চিরকাল টিকে থাকবে? যদিওবা সেটা হয় রক্ত-মাংসের গড়া বা রোবোটিক শরীর। 

বিষয়গুলো নিয়ে কৌতূহলী না হয়েও উপায় নেই। যদিও পৃথিবীর শেষ এখনও দূরে আছে বলেই মনে হচ্ছে। বর্তমানে মানব-সৃষ্ট নানা সমস্যায় জর্জরিত পৃথিবীতে আগে আমরা নিছক পৃথিবীতে টিকে থাকার সংগ্রাম নিয়ে চিন্তা করতাম। এখন ঘুরে গেছে সে চিন্তার মোড়। আমাদেরকে এখন আমাদের অস্তিতের মহাজাগতিক দিক নিয়ে ভাবতে হচ্ছে। দ্য লাস্ট থ্রি মিনিটস বইয়ে বলব ভবিষ্যত মহাবিশ্বের গল্প। বিখ্যাত কিছু পদার্থবিদ ও কসমোলজিস্টদের সর্বশেষ চিন্তার আলোকে সবচেয়ে সেরা অনুমানটুকুই আমরা তুলে ধরব। এটা কল্পনানির্ভর হবে না। সত্যি বলতে, ভবিষ্যতে নজিরবিহীন অনেক কিছুই ঘটতে পারে। কিন্তু ভুলে গেলে চলবে না, যেটা একবার অস্তিত্বে আসতে পারে, সেটা অস্তিত্ব হারাতেও পারে। 

এ বইটি সাধারণ পাঠকের জন্যে লেখা। বিজ্ঞান বা গণিতের কোনো পূর্ব জ্ঞান না থাকলেও চলবে। তবে, মাঝেমাঝেই আমাকে অনেক বড় বা অনেক ছোট সংখ্যা নিয়ে কথা বলতে হবে। এ ক্ষেত্রে ১০ এর ঘাত (পাওয়ার) ভিত্তিক সংক্ষিপ্ত গাণিতিক প্রতীক ব্যবহার করলে সুবিধা হবে। যেমন, দশ হাজার কোটিকে লিখতে গেলে ১০০,০০০,০০০,০০০ লিখতে হয়। এটা অসুবিধাজনক। এখানে ১ এর পরে ১১টি শূন্য আছে। ফলে, আমরা একে ১০১১ বা ১০ এর ১১তম ঘাত আকারে লিখতে পারি। একইভাবে দশ লক্ষ হলো ১০৬, এক লক্ষ কোটি হলো ১০১২ ইত্যাদি। তবে মনে রাখতে হবে, এই প্রতীকের মাধ্যমে সংখ্যাগুলোর বৃদ্ধির হার সরাসরি বোঝা কঠিন। ১০১২ সংখ্যাটি ১০১০ এর একশ গুণ। প্রায় একই মনে হলেও পার্থক্যটা কিন্তু বিশাল। ১০ এর পাওয়ার ঋণাত্মক বসিয়ে আবার খুব ছোট সংখ্যাদেরকেও প্রকাশ করা যায়। যেমন, একশ কোটির এক ভাগ বা ১/১,০০০,০০০,০০০ কে ১০-৯  (টেন টু দ্য পাওয়ার মাইনাস নাইন) লেখা যায়। কারণ, ভগ্নাংশের হরে ১ এর পরে ৯টি শূন্য আছে। 

শেষমেশ পাঠককে একটা কথা বলে রাখি। স্বাভাবিকভাবেই বইটির অনেকটাই অনুমান নির্ভর। হ্যাঁ, বইয়ের অধিকাংশ কথাই বর্তমান বিজ্ঞানের সেরা তথ্যের আলোকেই বলা হয়েছে। কিন্তু এরপরেও ভবিষ্যদের পূর্বাভাস অন্যান্য বৈজ্ঞানিক তথ্যের সমান মর্যাদা পেতে পারে না। তবুও মহাবিশ্বের চূড়ান্ত পরিণতি নিয়ে অনুমান করার লোভ সামলানো সম্ভব নয়। এই খোলা মনের আলোকেই বইটি লেখা। বৈজ্ঞানিকভাবে এ কথাগুলো মোটামুটি স্বীকৃত যে বিগ ব্যাং এর মাধ্যমে মহাবিশ্বের শুরু হয়েছে, এখন এটি শীতল ও প্রসারিত হতে হতে বিপরীত ধর্মের কোনো চূড়ান্ত অবস্থার দিকে এগিয়ে যাচ্ছে, অথবা হয়ত উন্মত্তভাবে সংকুচিত হয়ে যাবে। তবে যে সুদীর্ঘ সময় নিয়ে আমরা কথা বলছি, তাতে কোন ভৌত প্রক্রিয়া যে প্রভাবশালী ভূমিকা রাখবে তা খুব বেশি নিশ্চিত করে বলার সুযোগ নেই। সাধারণ নক্ষত্রের পরিণতি সম্পর্কে জ্যোতির্বিজ্ঞানীদের ধারণা মোটামুটি পরিষ্কার। নিউট্রন নক্ষত্র ও ব্ল্যাক হোলের মৌলিক বৈশিষ্ট্য সম্পর্কেও তাঁদের ধারণা দিন দিন সমৃদ্ধ হচ্ছে। কিন্তু যদি মহাবিশ্ব আরও লক্ষ কোটি বছর বা তারও বেশি সময় টিকে থাকে, তাহলে এতে এমন কোনো সূক্ষ্ম ভৌত প্রতিক্রিয়া ঘটতেও পারে, যা সম্পর্কে আমাদের অনুমান করা ছাড়া কিছু করার নেই। এক সময় হয়ত সেটাই হবে গুরুত্বপূর্ণ প্রতিক্রিয়া। 

প্রকৃতি সম্পর্কে আমাদের জ্ঞান কিন্তু অসম্পূর্ণ। ফলে মহাবিশ্বের চূড়ান্ত পরিণতি জানার চেষ্টা ও অনুমান করার উপায় আছে একটিই। আমাদের হাতে যেসব তত্ত্ব আছে সেগুলোকে কাজে লাগিয়েই যুক্তিভিত্তিক কোনো সিদ্ধান্তে পৌঁছতে হবে। কিন্তু এতেও সমস্যা আছে। মহাবিশ্বের পরিণতি বিষয়ক অনেকগুলো তত্ত্বেরই এখন পর্যন্ত প্রায়োগিক পরীক্ষা হয়নি। এমন কিছু বিষয়েও আলোচনা করেছি যেগুলো নিয়ে তাত্ত্বিকরা খুব আশাবাদী, কিন্তু এখনও তার প্রমাণ মেলেনি। যেমন, মহাকর্ষ তরঙ্গ নির্গমন [^1], প্রোটন ক্ষয় (proton decay) ও ব্ল্যাক হোল রেডিয়্যান্স। আবার একইভাবে এমন কোনো ভৌত প্রক্রিয়াও নিশ্চয়ই থাকবে যা আমরা এখন একেবারেই জানি না। হয়ত সেটা এ বইয়ের কথাগুলোকে বহুলাংশে পাল্টে দেবে। 

মহাবিশ্বে বৃদ্ধিমান প্রাণীর সম্ভাব্য কার্যক্রমের কথা ভাবলে এই অনিশ্চয়তাই আরও বড় হয়ে দেখা দেয়। এবারে আমরা বিজ্ঞান কল্পকাহিনির জগতে প্রবেশ করে ফেলেছি। তবুও এমনটাতো হতেই পারে যে কালের আবর্তনে এক সময় জীবিত প্রাণীরা ভৌত সিস্টেমের আচরণ ক্রমেই বড় পরিসরে উল্লেখযোগ্য রকম পরিবর্তন করে ফেলল। মহাবিশ্বের প্রাণ সম্পর্কেও আমি আলোচনা করেছি। কারণ, অনেক পাঠক মহাবিশ্বের পরিণতি জানতে চান মূলত মানুষ বা তার পরবর্তী প্রজন্মের পরিণতি জানার জন্যেই। তবে মনে রাখতে হবে মানুষের চেতনার প্রকৃতি সম্পর্কে এখনও বিজ্ঞানীরা সঠিক করে কিছুই জানেন না। এটাও জানা নেই যে দূর ভবিষ্যতে অস্তিত্ব টিকিয়ে রাখতে হলে চেতনার মধ্যে কোন কোন গুণাবলীগুলো থাকা প্রয়োজন। 

বইটির বিষয়বস্তু সম্পর্কে সহায়ক আলোচনায় অংশ নেওয়ার জন্যে কয়েকজন মানুষকে ধন্যবাদ দিতেই হয়। এঁরা হলেন জন ব্যারো, ফ্র্যাংক টিপলার, জ্যাসন টমলি, রজার পেনরোজ ও ডানকান স্টিল। সিরিজের সম্পাদক জেরি লিয়ন পাণ্ডুলিপি গুরুত্বের সাথে পড়ে দিয়েছিলেন। এজন্যে তাঁকেও ধন্যবাদ। চূড়ান্ত পাণ্ডুলিপিতে কাজ করার জন্যে স্যারা লিপিনকটকেও ধন্যবাদ। 

**অনুবাদকের নোট**

[^1]: ২০১৬ সালের ফেব্রুয়ারি মাসে এ তরঙ্গ পাওয়ার ঘোষণা দেওয়া হয়। অবশ্য পাওয়া গিয়েছিল আগের বছরের অক্টোবরেই। ফলে বইটির গুরুত্ব বাড়ল বলা চলে। 
